### ISSUE TITLE
T00 file

### ISSUE THREAD

**Issue by shozebhaider** [AllosterIt/GSAtools#1]
Hi, 

I am going through your tutorial. In 02_SA_statistics folder, where did you get the T00.lf_str.out file from ? In your executable shell file, you have the current folder 02_SA_statistics as the input directory. Even if I assume 01 to the data directory, 01_SA_encoding also doesn't generate this file. Can you please elaborate.

**Comment by jkleinj** [comment]
Hi,
thanks for the feedback,
I'll check that this weekend and get back to you.

**Comment by alepandini** [comment]
Hello,

the T00.lf_str.out is one of the pre-calculated files available in the tutorial folders. It includes 80,000 SA strings corresponding to 80,000 frames (in this specific case 80ns simulation). It is pre-calculated because the corresponding trajectory file would be to large to be included.

In general, by including some pre-calcualated files we can provide data for each step without the use of large files and/or long computational intermediate calculations.

I hope this clarify the issue. 

Best regards,
alessandro

**Comment by jkleinj** [comment]
Thanks Alessandro,
one additional comment (maybe stating the obvious): This type of file is the output of the encoding step in the tutorial's directory 01_SA_encoding (where you get 'T01.lf_str.out'). The short trajectory provided there would most likely not provide the mutual information required for a meaningful correlation analysis in the following steps of the tutorial. Therefore the jump to the encoded trajectory as Alessandro has explained.

By default GitHub limits file size to 50MB, but git-lfs enables storage of larger files. We may look into that for future updates of GSAtools.

I believe the question has been answered and close this issue.
